### ISSUE TITLE
Python script error

### ISSUE THREAD

**Issue by MichaelVLV** [michael-angerer/esp32_ble_ota#1]
Hello, I'm trying to run esp32_ble_ota/ble_client/main.py , but getting this error:

`  File "main.py", line 82`
`    while chunk := file.read(packet_size):`
    `                 ^`
`SyntaxError: invalid syntax`

Python 3.7.3 is installed on my PC.
Please, advice?

**Comment by michael-angerer** [comment]
Hi, 

The line throwing the error uses an assignment-expression introduced in Python 3.8: 
https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions

Would it be possible for you to upgrade the Python version?

**Comment by MichaelVLV** [comment]
Upgrading python to 3.8.0 fixed issue!
`Sending packet 8486/8486.`
`Sending OTA done.`
`ESP32: OTA done acknowledged.`
`OTA successful! Total time: 0:29:10.303657`
Thanks for hint.

**Comment by MichaelVLV** [comment]
Solution: need update python for 3.8.0 (or higher, not tested)
