### ISSUE TITLE
Revertion to factory after hard reset

### ISSUE THREAD

**Issue by txbugeater** [michael-angerer/esp32_ble_ota#2]
Hi Michael,

Great tutorial and example code!  It works great and I am able to transfer not only your example, but I am able to transfer my test app.  After it completes the transfer, the app reboots as intended and runs my app successfully.  

However, after I perform a hard reboot, it reverts back to the factory image.  I also transferred the stock hello_world.bin app and that runs as well the first time but then reverts to the factory partition without the hard reset when it calls esp_restart()

When I transfer the esp32_ble_ota.bin app it runs as well.  But when I hard reset it, I can no longer talk on the jtag/openocd interface.  I was able to transfer a new bin file.  Maybe its running out of the ota partition but I cannot be certain.  (BTW, I plan to toggle an IO and scope it out to determine what image is actually running I an experiment...)

I starting looking at the reference code and the gatt_svr.c code to see if I can figure out why.  I just started, but I thought I would just post an issue to see if you might have run into this or maybe someone else?

Thank you for any info you might have.

Dan

BTW,  I am running on an esp32-C3DevKitM-1

Note:  I moved to the usb interface and I can confirm that when loading the esp32_ble_ota.bin file the esp32 will use that partition.  I assume I must add something to my app to not have it revert to the factory image....

**Comment by txbugeater** [comment]
I found the problem (I should have read your tutorial more carefully!)  I needed to add the chuck of code to valid the image as you talked about in https://michaelangerer.dev/esp32/ble/ota/2021/06/08/esp32-ota-part-2.html (ESP32 Code / Main File)

**Comment by michael-angerer** [comment]
Hi Dan, 

Thank you for the kind words. I am glad it worked out for you. 

Best, 
Michael
