### ISSUE TITLE
unable to change advertised name

### ISSUE THREAD

**Issue by albrownwood** [michael-angerer/esp32_ble_ota#3]
Hi Michael,
Thanks for the project, it works pretty well on my side. One thing I am unable to change is the advertised device name, it seems to always defaults to "esp32".
So far I understand to only place to change in your code would be: 
`static const char device_name[] = "esp32";`

Anything I am missing?
Thanks

**Comment by michael-angerer** [comment]
Hi, 

I am glad you find my project useful! 

Maybe your app is caching the old name? 

You can set a device name programmatically using: 
`esp_ble_gap_set_device_name(const char *name);`

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv427esp_ble_gap_set_device_namePKc

**Comment by albrownwood** [comment]
I am calling ble_svc_gap_device_name_set() as you do in your project since the ble stack is Nimble. The api you mention seems to be the one for the bluedroid stack which does not seem available when NimBLE is selected in menuconfig.

**Comment by michael-angerer** [comment]
Right, my bad. 

Did you check if it is a problem with your BLE scanner?

**Comment by albrownwood** [comment]
good catch, I installed a BLE scanner on another device and the correct name is displayed. So there is very likely some caching going on with my dev machine since I initially tested with "esp32" as name. I will need to figure out how to clean the BLE cache on that machine.
Thanks!
